Updated docs to include google-ish formatted docstrings and improved guides
quant-aq/py-smps pull request #66
Opened 2023-07-07 04:09 UTC by dhhagan

Docs are automatically built upon creating a new release (well, currently manually triggered via github actions). To build and view locally for testing/reviewing purposes:

Checkout the branch locally and run:

```sh
$ cd docs
$ make clean
$ make HTML
$ cd ..
```

Navigate locally to the `docs/build/html` folder and open up the index or another HTML file and that should be what you need!

2023-07-11 15:06 UTC, dmcc requested changes
Thanks @dhhagan! New docs look great overall -- left various small changes (which are generally doc-focused). Please let me know if the review is too nit-picky, etc.

2023-07-12 11:37 UTC, dhhagan commented on README.md
>  ```py
Actually, I removed this section in favor of the later one.

2023-07-12 11:42 UTC, dhhagan commented on docs-archived/Makefile
Yea, that's a good question. I would love to be able to easily switch between version, but I don't know of a way to do that with the current architecture (github pages). It's fairly easy to do with ReadTheDocs, but we currently host on GitHub Pages. The old docs can always be viewed (or re-built) by checking out the release. I think this is something we can explore later on (and push throughout all of our repos), but might be out of scope for now.

2023-07-12 11:43 UTC, dhhagan commented on docs/source/api/generated/smps.AlphasenseOPCN2.__init__.rst
We don't *need* to as they are built via a GitHub Action after a release and moved to the `github-pages` branch, but we *can* if we want to.

2023-07-12 18:23 UTC, dmcc commented on docs/source/api/generated/smps.AlphasenseOPCN2.__init__.rst
Gotcha. Let me know if this sounds right -- my current sense is that there are two use cases:

1. Docs for released version (deployed via the flow you described)
2. Docs for dev versions (could be pre-built or not)

I think I lean towards not prebuilding in case 2 since it it's an extra step to keep the prebuilt docs fresh + adds some minor reviewing complexity + someone getting a GitHub checkout is presumably working in a dev capacity and could build them as needed.

(all this said, not a super firmly held opinion 😄 )

2023-07-13 14:55 UTC, dhhagan commented on README.md
> +# Dependencies
Added to the docs section.

2023-07-13 15:23 UTC, dhhagan commented on docs/source/guides/Getting Started.ipynb
> +    "obj.integrate(weight='mass', dmin=0., dmax=1., rho=1.65)"
Fixed the text above to match.

2023-07-13 15:30 UTC, dhhagan commented on docs/source/guides/Visualizations.ipynb
> +    "  You may not agree with the default colormap choice (`viridis`), but you can easily change it as you see fit. However, you can't use `jet`!\n",
Updated.

2023-07-13 15:59 UTC, dmcc approved these changes
LGTM, thanks for the iteration!

2023-07-13 16:00 UTC, merged